CREATE DATABASE IF NOT EXISTS worldcup
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE worldcup;

CREATE TABLE IF NOT EXISTS worldcup_app_state (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  data JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS worldcup_members (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(100) DEFAULT '',
  group_id VARCHAR(64) DEFAULT '',
  group_name VARCHAR(120) DEFAULT '',
  status VARCHAR(32) DEFAULT 'online',
  avatar_url VARCHAR(255) DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS worldcup_groups (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  member_count INT NOT NULL DEFAULT 0,
  heat INT NOT NULL DEFAULT 0,
  status VARCHAR(32) DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS worldcup_latest_matches (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  match_id VARCHAR(64) NOT NULL,
  home VARCHAR(120) NOT NULL,
  away VARCHAR(120) NOT NULL,
  group_name VARCHAR(64) DEFAULT '',
  time VARCHAR(64) DEFAULT '',
  venue VARCHAR(160) DEFAULT '',
  status VARCHAR(32) DEFAULT 'open',
  final_score VARCHAR(16) DEFAULT '',
  kickoff_at VARCHAR(64) DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO worldcup_app_state (id, data)
VALUES ('main', '{}')
ON DUPLICATE KEY UPDATE data = VALUES(data);
